# Generated by Django 5.2.7 on 2025-10-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente (opcional)', max_length=20, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, help_text='Edad del cliente (opcional)', null=True)),
            ],
        ),
    ]
